services:
  - type: web
    name: nas-cloud-simulation
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon # Choose the region closest to your users
    plan: free # You can change this to a paid plan if needed
    numInstances: 1
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
    autoDeploy: true
