services:
  - type: web
    name: nas-cloud-simulation-api
    env: java
    buildCommand: 'mvnw -ntp clean package'
    startCommand: 'java -jar target/NasCloudSimulation-0.0.1-SNAPSHOT.jar'
    branch: main
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
    instances: 1
    plan: free
    autoDeploy: true
